#!/bin/bash

Help()
{
   # Display Help
   echo
   echo "Run a temporary container."
   echo "Default command run by script: docker run --rm -it DOCKER_IMAGE /bin/bash" 
   echo
   echo "Syntax: tempc [-h|n:|p:|s|v] [-- OTHER_DOCKER_ARGUMENTS] DOCKER_IMAGE"
   echo "Example: tempc -n server -- --net my-net --ip 172.18.50.50 ubuntu"
   echo "options:"
   echo "h       Print this Help."
   echo "n NAME  Set container name and hostname."
   echo "p PORT  Set shared ports. PORT should be in the same format as docker -p argument, HOST_PORT:CONTAINER_PORT"
   echo "s       Create shared volume at \$PWD:/home/\$USER/shared."
   echo "v       Print software version."
   echo
}

Version(){
   echo "Version $1"
}

EchoYellow(){
   echo -e "\033[33m$1\033[0m"
}

############################################################
############################################################
# Main program                                             #
############################################################
############################################################

# Declare arguments array
declare -a args=()

# Get the options
while getopts ":hn:p:sv" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      n) # set container name
         # Add name argument
         CONTAINER_NAME=$OPTARG
         args+=("--name=$CONTAINER_NAME --hostname=$CONTAINER_NAME");;
      p) # set ports
         # Add ports argument
         CONTAINER_PORTS=$OPTARG
         args+=("-p $CONTAINER_PORTS");;
      s) # create shared volume
         # Add shared volume arguments
         CONTAINER_SHARED_DIR="/home/$USER/shared"
         HOST_SHARED_DIR=$PWD
         EchoYellow "WARNING: creating SHARED VOLUME between host and container"
         EchoYellow "Any changes made on container's $CONTAINER_SHARED_DIR directory will be applied to host's $HOST_SHARED_DIR directory."
         args+=("--workdir=$CONTAINER_SHARED_DIR")
         args+=("-v $HOST_SHARED_DIR:$CONTAINER_SHARED_DIR");;

      v) # display version
         Version;
         exit;;
   #   \?) # Append extra options
   #       echo "$OPT $OPTARG"
   #       exit;;
   esac
done

shift $(($OPTIND - 1))

REMAINING_ARGS=$@
echo "$REMAINING_ARGS"

if [[ -z ${REMAINING_ARGS} ]]; then
   echo "No image provided."
   Help
   exit
fi

# Add image argument
args+=("$REMAINING_ARGS /bin/bash")

if [ -z $CONTAINER_NAME ]; then
   echo "Creating container with random name. For naming options run tempc -h."
else
   echo $CONTAINER_NAME
fi

# Run container
docker run --rm -it \
   $(echo "${args[@]}")

