#!/bin/bash

RunContainer() {

DOCKER_IMAGE=${1:?"missing arg 1 for DOCKER_IMAGE"}
SHARED=$2
CONTAINER_SHARED_DIR="/home/$USER/shared"
HOST_SHARED_DIR=$PWD

if [ $SHARED = "1" ]; then
   EchoYellow "WARNING: creating SHARED VOLUME between host and container"
   EchoYellow "Any changes made on container's $CONTAINER_SHARED_DIR directory will be applied to host's $HOST_SHARED_DIR directory."

   docker run --rm -it \
      --workdir=$CONTAINER_SHARED_DIR \
      -v $HOST_SHARED_DIR:$CONTAINER_SHARED_DIR \
      $DOCKER_IMAGE /bin/bash 
else
   docker run --rm -it \
      $DOCKER_IMAGE /bin/bash 
fi
}


Help()
{
   # Display Help
   echo \
"Run a temporary container with shared volume."
   echo
   echo "Syntax: tempc [-h|s|v] DOCKER_IMAGE"
   echo "options:"
   echo "h     Print this Help."
   echo "s     Create shared volume at \$PWD:/home/\$USER/shared."
   echo "v     Print software version and exit."
   echo
}

Version(){
   echo "Version $1"
}

EchoYellow(){
   echo -e "\033[33m$1\033[0m"
}

############################################################
############################################################
# Main program                                             #
############################################################
############################################################

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    Help;
    exit;
fi

SHARED=0;

# Get the options
while getopts ":hsv" option; do
   case $option in
      h) # display Help
         Help
         exit;;
      s) # create shared volume
         SHARED=1;;
      v) # display version
         Version 0.0;
         exit;;
     \?) # Invalid option
         echo "Error: Invalid option"
         exit;;
   esac
done

shift $(($OPTIND - 1))

RunContainer $1 $SHARED



